version: '3'
services:
  workman:
    command: /bin/sh -c 'npm run startdev'
    image: node:8
    working_dir: /opt
    ports:
      - "3000:3000"
    volumes:
      - .:/opt
    networks:
      - service
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .mongo:/data/db
    networks:
      - mongo

networks:
  service:
  mongo: